### PR TITLE
Mux improvements for tlog

### PR DESCRIPTION
**Pull request by richm**
@spbnick @nhosoi PTAL

### CODE REVIEW

**Comment by spbnick** [comment]
This looks good to me, as far as I can understand.

**Comment by richm** [comment]
@nhosoi If this looks ok to you, I will merge it.

**Comment by nhosoi** [comment]
Looks great.

I have one question about the default value of the environment variable MUX_CPU_LIMIT.
+MUX_CPU_LIMIT=${MUX_CPU_LIMIT:-1}

I'd think the unit is millisec like this:
  openshift_logging_curator_cpu_limit: 100m

And it turned out MUX is having a hard time to catch up with the value 100m and we are planning to set some higher value (e.g., 500m) as default.

**Comment by richm** [comment]
@nhosoi Right - the unit is m - Does that mean just a plain `1` means one entire core?  Because that's what I want - mux should use an entire core.

**Comment by richm** [comment]
Decided to leave it as `500m` for now.

**Pull request merged**
